`timescale 1ns / 1ps

/*
 * Opcode Decoder
Ye module Operation code generate karta hai jo Control unit use karta hai Jisse Testbench Execute karta hai . 

 * NOP: 0000, //0
 
   ADD: 0001, //1 ALU
   
   SUB: 0010, //2 ALU
   
   LOAD: 0011, //3  Memory
   
   STORE: 0100 //4 Memory
   
 */
module opcode_decoder (
    input [3:0] Opcode,
    
    output is_ADD, // outputs are defiend e.g ADD,SUB,LOAD,STORE,NOP
    
    output is_SUB,
    
    output is_LOAD,
    
    output is_STORE,
    
    output is_NOP
);

    // Opcodes are used in testbench
        parameter OP_NOP   = 4'b0000;
        
    parameter OP_ADD   = 4'b0001;
    
    parameter OP_SUB   = 4'b0010;
    
        parameter OP_LOAD  = 4'b0011;
        
    parameter OP_STORE = 4'b0100;
// Yahape sahi hai kya ->
    // Combinational logic 
    assign is_ADD   = (Opcode == OP_ADD); // here we set which operation is generated by the opcode this goes into contorol unit
    
    assign is_SUB   = (Opcode == OP_SUB);
    
    assign is_LOAD  = (Opcode == OP_LOAD);
    
    assign is_STORE = (Opcode == OP_STORE);
    
    assign is_NOP   = (Opcode == OP_NOP);
    
endmodule
